name: Request New Feature
description: Request New Feature
title: "[Request New Feature]: "
labels: ["Request New Feature"]
body:
  - type: markdown
    attributes:
      value: |
        A la brevedad estaremos revisando la solicitud, en caso de necesitar podes cantactarnos por medio del channel de slack #help-feature-store!
  - type: input
    id: contact
    attributes:
      label: Email Contacto
      description: Email del team o responsable, para poder contactar.
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: entity
    attributes:
      label: Entidad
      description: Nombre de la entidad a crear.
      placeholder: ex. account
    validations:
      required: true
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción
      description: Breve descripción del cambio (archivos, enteidades, etc.)
      render: shell
    validations:
      required: true
  - type: textarea
    id: motivo
    attributes:
      label: Motivo
      description: Breve descripción del motivo del cambio.
      render: shell
    validations:
      required: true
