name: Request Optimization
description: Request Optimization
title: "[Request Optimization]: "
labels: ["Request Optimization"]
body:
  - type: markdown
    attributes:
      value: |
        Formato para optimizar Entidades en Feature Store. A la brevedad estaremos revisando la solicitud, en caso de necesitarlo, puede contactarnos por medio del channel de slack #help-feature-store!
  - type: input
    id: contact
    attributes:
      label: Email Contacto
      description: Email del team o responsable, para poder contactar.
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: dropdown
    id: entities
    attributes:
      label: Entidades
      description: Entidad impactada por la optimizaci贸n
      options:
        - account
        - bankwithdrawals
        - bureaus
        - ccardaggpercat
        - contactcollection
        - coronavaucher
        - creditcard
        - credits
        - devices
        - flags
        - funding
        - merchantsbehavior
        - names
        - navigation
        - notifications
        - payments
        - prepaid
        - sellerclassification
        - sellers
        - shipments
        - sociodemographic
        - userpix
        - Universo
    validations:
      required: true
  - type: textarea
    id: descripcion
    attributes:
      label: Descripci贸n
      description: Breve descripci贸n del cambio (archivos, entidades, etc.)
      render: shell
    validations:
      required: true
  - type: textarea
    id: motivo
    attributes:
      label: Motivo
      description: Breve descripci贸n del motivo del cambio.
      render: shell
    validations:
      required: true
